export const SAVE_MESSAGE_DISPATCH = 'SAVE_MESSAGE_DISPATCH'
export const SAVE_MESSAGE_SUCCESS = 'SAVE_MESSAGE_SUCCESS'
export const SAVE_MESSAGE_FAIL = 'SAVE_MESSAGE_FAIL'

export const GET_MESSAGE_DISPATCH = 'GET_MESSAGE_DISPATCH'
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS'
export const GET_MESSAGE_FAIL = 'GET_MESSAGE_FAIL'

export const DELETE_MESSAGE_DISPATCH = 'DELETE_MESSAGE_DISPATCH'
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS'
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL'